'use client';

import { ConnectButton } from '@rainbow-me/rainbowkit';
import { waitForTransactionReceipt } from '@wagmi/core';
import { useRouter } from 'next/navigation';
import { useEffect, useMemo, useState } from 'react';
import { formatUnits, isAddress, parseUnits, type Address } from 'viem';
import { useAccount, useChainId, usePublicClient, useReadContract, useWriteContract, useSwitchChain } from 'wagmi';
import { toast } from 'sonner';
import { secPayPoolAbi, mockUsdcAbi } from '@/contracts/abis';
import { deployedAddresses } from '@/contracts/deployment';
import { appChain, wagmiConfig } from '@/lib/wagmi';

const poolAddress = deployedAddresses.secPayPool as Address;
const tokenAddress = deployedAddresses.mockUSDC as Address;
const unset = /^0x0{40}$/i.test(poolAddress);
const short = (value?: string) => value ? `${value.slice(0, 6)}…${value.slice(-4)}` : '—';
const money = (value: bigint | undefined, digits = 2) => value === undefined ? '…' : Number(formatUnits(value, 6)).toLocaleString(undefined, { maximumFractionDigits: digits });
const txUrl = (hash: string) => `https://${appChain.id === 8453 ? '' : 'sepolia.'}basescan.org/tx/${hash}`;
type PoolInfo = { employer: Address; token: Address; poolBalance: bigint; payPeriodStart: bigint; payPeriodEnd: bigint; pausedAt: bigint; totalPausedDuration: bigint; totalMonthlyObligations: bigint; reservedBalance: bigint; active: boolean; paused: boolean };
type Employee = { monthlySalary: bigint; ratePerSecond: bigint; lastWithdrawTime: bigint; accruedStored: bigint; streamEnd: bigint; reserved: bigint; exists: boolean; active: boolean };

function Card({ children, className = '' }: { children: React.ReactNode, className?: string }) { return <section className={`card ${className}`}>{children}</section>; }
function Copy({ value }: { value: string }) { return <button className="text-xs text-mint hover:underline" onClick={() => { navigator.clipboard.writeText(value); toast.success('Address copied'); }}>Copy</button>; }

function TransactionButton({ label, onClick, disabled = false }: { label: string; onClick: () => Promise<void>; disabled?: boolean }) {
  const [busy, setBusy] = useState(false);
  return <button className="btn" disabled={busy || disabled} onClick={async () => { setBusy(true); await onClick(); setBusy(false); }}>{busy ? 'Confirm in wallet…' : label}</button>;
}

function LiveAmount({ base, rate, endAt }: { base: bigint; rate: bigint; endAt?: number }) {
  const [value, setValue] = useState(base);
  useEffect(() => {
    setValue(base); const began = Date.now(); let frame = 0;
    const tick = () => { const cappedNow = endAt ? Math.min(Date.now(), endAt) : Date.now(); const elapsedMs = BigInt(Math.max(0, cappedNow - began)); setValue(base + (rate * elapsedMs / 1_000n / 1_000_000_000_000_000_000n)); frame = requestAnimationFrame(tick); };
    frame = requestAnimationFrame(tick); return () => cancelAnimationFrame(frame);
  }, [base, rate, endAt]);
  return <>{money(value, 6)}</>;
}

export default function Home() {
  const { address, isConnected } = useAccount(); const chainId = useChainId(); const publicClient = usePublicClient();
  const { writeContractAsync } = useWriteContract();
  const [notice, setNotice] = useState(''); const [now, setNow] = useState(Date.now()); const [screen, setScreen] = useState<'choose' | 'employer' | 'employee'>('choose');
  const wrongNetwork = isConnected && chainId !== appChain.id;
  useEffect(() => { const interval = setInterval(() => setNow(Date.now()), 1000); const sync = () => setNow(Date.now()); window.addEventListener('focus', sync); return () => { clearInterval(interval); window.removeEventListener('focus', sync); }; }, []);
  const employerPools = useReadContract({ address: poolAddress, abi: secPayPoolAbi, functionName: 'getEmployerPools', args: [address || '0x0000000000000000000000000000000000000000'], query: { enabled: !!address && !unset, staleTime: 15_000 } });
  const employeePools = useReadContract({ address: poolAddress, abi: secPayPoolAbi, functionName: 'getEmployeePools', args: [address || '0x0000000000000000000000000000000000000000'], query: { enabled: !!address && !unset, staleTime: 15_000 } });
  const employerIds = employerPools.data as readonly bigint[] | undefined; const employeeIds = employeePools.data as readonly bigint[] | undefined;
  const poolId = (screen === 'employer' ? employerIds?.[0] : employeeIds?.[0]) || 0n;
  const poolRead = useReadContract({ address: poolAddress, abi: secPayPoolAbi, functionName: 'getPoolInfo', args: [poolId], query: { enabled: poolId > 0n, staleTime: 10_000 } });
  const employeeRead = useReadContract({ address: poolAddress, abi: secPayPoolAbi, functionName: 'getEmployees', args: [poolId], query: { enabled: poolId > 0n, staleTime: 10_000 } });
  const balanceRead = useReadContract({ address: tokenAddress, abi: mockUsdcAbi, functionName: 'balanceOf', args: [address || '0x0000000000000000000000000000000000000000'], query: { enabled: !!address && !unset, staleTime: 10_000 } });
  const allowanceRead = useReadContract({ address: tokenAddress, abi: mockUsdcAbi, functionName: 'allowance', args: [address || '0x0000000000000000000000000000000000000000', poolAddress], query: { enabled: !!address && !unset, staleTime: 10_000 } });
  const pool = poolRead.data as PoolInfo | undefined;
  const employeeTuple = employeeRead.data as unknown as [Address[], Employee[], bigint[]] | undefined;
  const myIndex = employeeTuple?.[0].findIndex((a) => a.toLowerCase() === address?.toLowerCase()) ?? -1;
  const me = myIndex >= 0 ? employeeTuple?.[1][myIndex] : undefined;
  const accrued = myIndex >= 0 ? employeeTuple?.[2][myIndex] || 0n : 0n;
  const [history, setHistory] = useState<{ amount: bigint; hash: string }[]>([]);
  useEffect(() => { if (!publicClient || !address || !poolId || unset) return; let cancelled = false; (async () => { try { const event = secPayPoolAbi.find((item) => item.type === 'event')!; const logs = await publicClient.getLogs({ address: poolAddress, event: event as never, args: { poolId, employee: address } as never, fromBlock: 'earliest' }); if (!cancelled) setHistory(logs.map((l: any) => ({ amount: l.args.amount as bigint, hash: l.transactionHash }))); } catch { /* RPC providers may limit historic logs; the dashboard still functions. */ } })(); return () => { cancelled = true; }; }, [publicClient, address, poolId]);
  const refresh = () => { employerPools.refetch(); employeePools.refetch(); poolRead.refetch(); employeeRead.refetch(); balanceRead.refetch(); allowanceRead.refetch(); };
  const transact = async (label: string, request: object): Promise<void> => { try { setNotice(`${label}: awaiting wallet confirmation`); const hash = await writeContractAsync(request as never); toast.loading(label, { id: hash, description: <a href={txUrl(hash)} target="_blank" className="underline">View on BaseScan</a> }); await waitForTransactionReceipt(wagmiConfig, { hash }); toast.success(`${label} confirmed`, { id: hash }); setNotice(`${label} confirmed`); refresh(); } catch (error: any) { const message = error?.shortMessage || error?.message || `${label} failed`; toast.error(message); setNotice(message); } };

  useEffect(() => { if (!isConnected) setScreen('choose'); }, [isConnected]);
  if (!isConnected) return <Landing />;
  if (wrongNetwork) return <WrongNetwork />;
  if (unset) return <main className="mx-auto max-w-xl px-5 py-24"><Card><h1 className="text-2xl font-bold">Deployment required</h1><p className="mt-3 text-slate-300">Set <code>NEXT_PUBLIC_SECPAY_POOL_ADDRESS</code> and <code>NEXT_PUBLIC_MOCK_USDC_ADDRESS</code> after running the Foundry deployment script.</p></Card></main>;
  return <main className="mx-auto min-h-screen max-w-6xl px-4 py-6 sm:px-8"><Header balance={balanceRead.data as bigint | undefined} onBack={screen === 'choose' ? undefined : () => setScreen('choose')} />{notice && <p className="my-4 text-sm text-slate-400" aria-live="polite">{notice}</p>}{screen === 'choose' ? <RoleSelection address={address as Address} hasEmployerPool={!!employerIds?.length} hasEmployeePool={!!employeeIds?.length} onEmployer={() => setScreen('employer')} onEmployee={() => setScreen('employee')} /> : screen === 'employer' ? (employerIds?.length ? <Employer poolId={poolId} pool={pool} employees={employeeTuple} allowance={allowanceRead.data as bigint | undefined} transact={transact} now={now} /> : <EmployerSetup transact={transact} />) : (employeeIds?.length ? <EmployeeDashboard poolId={poolId} pool={pool} employee={me} accrued={accrued} history={history} transact={transact} now={now} /> : <EmployeeWaiting address={address as Address} />)}<div className="mt-5">{appChain.id === 84532 && <TransactionButton label="Get test mUSDC" onClick={() => transact('Faucet', { address: tokenAddress, abi: mockUsdcAbi, functionName: 'faucet' })} />}</div></main>;
}

function Header({ balance, onBack }: { balance?: bigint; onBack?: () => void }) {
  const router = useRouter();
  const goBack = () => onBack ? onBack() : window.history.length > 1 ? router.back() : router.push('/');
  return <header className="flex items-center justify-between gap-3 border-b border-white/10 pb-5"><div className="flex items-center gap-3"><button aria-label="Go back" className="rounded-lg border border-white/15 px-2.5 py-1.5 text-sm text-slate-300 hover:border-mint hover:text-mint" onClick={goBack}>← Back</button><div><span className="text-xl font-black tracking-tight">sec<span className="text-mint">pay</span></span><p className="text-xs text-slate-400">Real-time payroll on Base</p></div></div><div className="flex items-center gap-3"><span className="hidden text-sm text-slate-300 sm:block">{money(balance)} mUSDC</span><ConnectButton showBalance={false} /></div></header>;
}
function Landing() { return <main className="relative mx-auto flex min-h-screen max-w-5xl flex-col justify-center overflow-hidden px-6"><div className="absolute -top-32 right-0 h-96 w-96 rounded-full bg-mint/15 blur-3xl"/><p className="relative text-sm font-semibold uppercase tracking-[.2em] text-mint">Built for Base</p><h1 className="relative mt-4 max-w-3xl text-5xl font-black leading-tight sm:text-7xl">Salary should arrive <span className="text-mint">as you earn it.</span></h1><p className="relative mt-6 max-w-xl text-lg leading-8 text-slate-300">SecPay lets employers fund payroll once, while every employee earns a visible, withdrawable balance every second.</p><div className="relative mt-9"><ConnectButton label="Connect Wallet" showBalance={false} /></div><div className="relative mt-16 grid gap-4 sm:grid-cols-3"><Card><b>30-day payroll</b><p className="mt-2 text-sm text-slate-400">Fund a secure on-chain pool.</p></Card><Card><b>Continuous earning</b><p className="mt-2 text-sm text-slate-400">Balances animate locally, no RPC spam.</p></Card><Card><b>Instant liquidity</b><p className="mt-2 text-sm text-slate-400">Withdraw earned mUSDC anytime.</p></Card></div></main>; }
function WrongNetwork() { const { switchChain, isPending } = useSwitchChain(); return <main className="mx-auto max-w-xl px-5 py-24"><Card><h1 className="text-2xl font-bold">Switch to {appChain.name}</h1><p className="mt-2 text-slate-300">SecPay is configured for Base Sepolia.</p><button className="btn mt-5" disabled={isPending} onClick={() => switchChain({ chainId: appChain.id })}>{isPending ? 'Switching…' : `Switch to ${appChain.name}`}</button></Card></main>; }
function RoleSelection({ address, hasEmployerPool, hasEmployeePool, onEmployer, onEmployee }: { address: Address; hasEmployerPool: boolean; hasEmployeePool: boolean; onEmployer: () => void; onEmployee: () => void }) { return <div className="mx-auto mt-14 max-w-3xl"><p className="text-center text-sm font-semibold uppercase tracking-[.18em] text-mint">Welcome to SecPay</p><h1 className="mt-3 text-center text-3xl font-bold sm:text-4xl">What would you like to do?</h1><p className="mx-auto mt-3 max-w-xl text-center text-slate-400">Choose a workspace. You can return here at any time using Back.</p><div className="mt-8 grid gap-5 sm:grid-cols-2"><Card><h2 className="text-2xl font-bold">I’m an Employer</h2><p className="mt-2 text-slate-400">{hasEmployerPool ? 'Manage your staff, fund payroll, and control streams.' : 'Create a payroll pool, add your team, and fund their next 30 days.'}</p><div className="mt-5"><button className="btn" onClick={onEmployer}>{hasEmployerPool ? 'Open employer dashboard' : 'Create a payroll pool'}</button></div></Card><Card><h2 className="text-2xl font-bold">I’m an Employee</h2><p className="mt-2 text-slate-400">{hasEmployeePool ? 'See what you have earned and withdraw it to this wallet.' : 'Your employer must add this wallet before earnings can start.'}</p><div className="mt-5"><button className="btn" onClick={onEmployee}>{hasEmployeePool ? 'Open employee dashboard' : 'Show my receiving address'}</button></div></Card></div><p className="mt-6 break-all rounded-lg bg-black/20 p-3 text-center font-mono text-xs text-slate-300">{address} <Copy value={address}/></p></div>; }
function EmployerSetup({ transact }: { transact: (label: string, request: object) => Promise<void> }) { return <div className="mx-auto mt-14 max-w-xl"><Card><p className="text-sm font-semibold uppercase tracking-[.18em] text-mint">Employer setup</p><h1 className="mt-2 text-3xl font-bold">Create your payroll pool</h1><p className="mt-3 text-slate-400">After it is created, add each employee’s receiving wallet, deposit mUSDC, then start the 30-day pay period.</p><div className="mt-6"><TransactionButton label="Create payroll pool" onClick={() => transact('Create pool', { address: poolAddress, abi: secPayPoolAbi, functionName: 'createPool' })} /></div></Card></div>; }
function EmployeeWaiting({ address }: { address: Address }) { return <div className="mx-auto mt-14 max-w-xl"><Card><p className="text-sm font-semibold uppercase tracking-[.18em] text-mint">Employee setup</p><h1 className="mt-2 text-3xl font-bold">Give this address to your employer</h1><p className="mt-3 text-slate-400">Your employer must add this receiving address, fund the pool, and start the pay period. Once that happens, your earned balance will begin increasing every second and you can withdraw it directly to this wallet.</p><p className="mt-5 break-all rounded-lg bg-black/20 p-3 font-mono text-xs">{address}</p><Copy value={address}/></Card></div>; }

function Employer({ poolId, pool, employees, allowance, transact, now }: { poolId: bigint; pool?: PoolInfo; employees?: [Address[], Employee[], bigint[]]; allowance?: bigint; transact: (label:string, request:object)=>Promise<void>; now:number }) {
  const [worker, setWorker] = useState(''); const [salary, setSalary] = useState(''); const [deposit, setDeposit] = useState('');
  const add = async (): Promise<void> => { if (!isAddress(worker) || !salary) { toast.error('Enter a valid wallet and salary'); return; } await transact('Add employee', { address: poolAddress, abi: secPayPoolAbi, functionName:'addEmployee', args:[poolId, worker, parseUnits(salary, 6)] }); setWorker(''); setSalary(''); };
  const fund = async () => { if (!deposit) return; const amount = parseUnits(deposit, 6); if ((allowance || 0n) < amount) await transact('Approve mUSDC', { address: tokenAddress, abi: mockUsdcAbi, functionName:'approve', args:[poolAddress, amount] }); await transact('Fund pool', { address:poolAddress, abi:secPayPoolAbi, functionName:'deposit', args:[poolId, amount] }); setDeposit(''); };
  const toggleStream = async (): Promise<void> => { if (!pool) return; if (!pool.paused && !confirm('Stop this payroll stream? Employees stop accruing until you resume it.')) return; await transact(pool.paused ? 'Resume stream' : 'Stop stream', { address:poolAddress, abi:secPayPoolAbi, functionName:pool.paused ? 'unpausePool' : 'pausePool', args:[poolId] }); };
  const funded = !!pool && pool.poolBalance >= pool.reservedBalance;
  return <div className="mt-7 space-y-5"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-sm text-mint">Employer dashboard · Pool #{poolId.toString()}</p><h1 className="text-3xl font-bold">Your payroll, in motion.</h1></div><p className="text-sm text-slate-400">{pool?.active ? `Ends ${new Date(Number(pool.payPeriodEnd)*1000).toLocaleDateString()}` : 'Ready to fund'}</p></div><div className="grid gap-5 lg:grid-cols-3"><Card><p className="text-sm text-slate-400">Monthly obligation</p><p className="mt-2 text-2xl font-bold">{money(pool?.totalMonthlyObligations)} mUSDC</p></Card><Card><p className="text-sm text-slate-400">Available pool balance</p><p className="mt-2 text-2xl font-bold">{money(pool?.poolBalance)} mUSDC</p></Card><Card><p className="text-sm text-slate-400">Status</p><p className="mt-2 text-2xl font-bold text-mint">{pool?.paused ? 'Stopped' : pool?.active ? 'Streaming' : funded ? 'Funded' : 'Needs funding'}</p></Card></div><div className="grid gap-5 lg:grid-cols-2"><Card><h2 className="font-bold">Add an employee</h2><div className="mt-4 grid gap-3 sm:grid-cols-[1fr_150px_auto]"><input className="field" value={worker} onChange={e=>setWorker(e.target.value)} placeholder="0x wallet address"/><input className="field" value={salary} onChange={e=>setSalary(e.target.value)} placeholder="mUSDC / month" inputMode="decimal"/><TransactionButton label="Add" onClick={add}/></div></Card><Card><h2 className="font-bold">Fund payroll</h2><div className="mt-4 flex gap-3"><input className="field" value={deposit} onChange={e=>setDeposit(e.target.value)} placeholder="Amount in mUSDC" inputMode="decimal"/><TransactionButton label="Approve & deposit" onClick={fund}/></div><div className="mt-4 flex flex-wrap gap-2"><TransactionButton disabled={!funded || !!pool?.active} label="Start pay period" onClick={() => transact('Start pay period', {address:poolAddress,abi:secPayPoolAbi,functionName:'startPayPeriod',args:[poolId]})}/>{pool?.active && <TransactionButton label={pool.paused ? 'Resume stream' : 'Stop stream'} onClick={toggleStream}/>}</div></Card></div><EmployeeTable poolId={poolId} rows={employees} active={!!pool?.active} transact={transact} now={now}/></div>;
}

function EmployeeTable({ poolId, rows, active, transact }: { poolId:bigint; rows?:[Address[],Employee[],bigint[]]; active:boolean; transact:(label:string,request:object)=>Promise<void>; now:number }) { const addresses=rows?.[0]||[]; const data=rows?.[1]||[]; const accrued=rows?.[2]||[]; return <Card><h2 className="font-bold">Employees</h2><div className="mt-4 hidden overflow-x-auto md:block"><table className="w-full text-left text-sm"><thead className="text-slate-400"><tr><th>Wallet</th><th>Monthly salary</th><th>Accrued</th><th>Status</th><th/></tr></thead><tbody>{addresses.map((a,i)=><tr className="border-t border-white/10" key={a}><td className="py-4 font-mono">{short(a)} <Copy value={a}/></td><td>{money(data[i].monthlySalary)}</td><td>{money(accrued[i])}</td><td className="text-mint">{data[i].active && active ? 'Streaming' : 'Stopped'}</td><td className="space-x-2"><button className="text-rose-300" onClick={()=>confirm('Stop this employee’s stream?')&&transact('Remove employee',{address:poolAddress,abi:secPayPoolAbi,functionName:'removeEmployee',args:[poolId,a]})}>Remove</button><button className="text-mint" onClick={()=>{const v=prompt('New monthly salary in mUSDC'); if(v) transact('Update salary',{address:poolAddress,abi:secPayPoolAbi,functionName:'updateSalary',args:[poolId,a,parseUnits(v,6)]});}}>Edit</button></td></tr>)}</tbody></table></div><div className="mt-4 grid gap-3 md:hidden">{addresses.map((a,i)=><div className="rounded-xl bg-white/5 p-4" key={a}><div className="flex justify-between"><span className="font-mono">{short(a)}</span><Copy value={a}/></div><p className="mt-2 text-sm">{money(data[i].monthlySalary)} mUSDC/month · <span className="text-mint">{money(accrued[i])} earned</span></p><div className="mt-3 flex gap-4"><button className="text-sm text-rose-300" onClick={()=>confirm('Stop stream?')&&transact('Remove employee',{address:poolAddress,abi:secPayPoolAbi,functionName:'removeEmployee',args:[poolId,a]})}>Remove</button></div></div>)}</div>{!addresses.length && <p className="py-8 text-center text-slate-500">No employees yet.</p>}</Card>; }

function EmployeeDashboard({ poolId, pool, employee, accrued, history, transact, now }: { poolId:bigint; pool?:PoolInfo; employee?:Employee; accrued:bigint; history:{amount:bigint;hash:string}[]; transact:(label:string,request:object)=>Promise<void>; now:number }) { const end=Number(pool?.payPeriodEnd||0n)*1000; const start=Number(pool?.payPeriodStart||0n)*1000; const streaming = !!pool?.active && !pool?.paused && now < end; const progress=end>start ? Math.min(100,Math.max(0,(now-start)/(end-start)*100)) : 0; return <div className="mx-auto mt-10 max-w-3xl space-y-5"><Card className="overflow-hidden bg-gradient-to-br from-panel to-emerald-950/40"><p className="text-sm uppercase tracking-[.18em] text-mint">Available to withdraw</p><p className="mt-3 text-5xl font-black sm:text-7xl"><LiveAmount base={accrued} rate={streaming ? employee?.ratePerSecond || 0n : 0n} endAt={end}/><span className="ml-2 text-xl text-slate-300">mUSDC</span></p><p className="mt-4 text-slate-300">You earn every second. Your wallet receives the mUSDC when you press Withdraw; the amount above keeps ticking between secure on-chain syncs.</p><div className="mt-6"><TransactionButton disabled={!pool?.active || accrued===0n} label={`Withdraw ${money(accrued, 6)} mUSDC`} onClick={() => transact('Withdraw earnings', {address:poolAddress,abi:secPayPoolAbi,functionName:'withdraw',args:[poolId]})}/></div></Card><div className="grid gap-5 sm:grid-cols-2"><Card><p className="text-sm text-slate-400">Monthly salary</p><p className="mt-2 text-2xl font-bold">{money(employee?.monthlySalary)} mUSDC</p><p className="mt-2 text-sm text-slate-400">{employee ? (Number(employee.ratePerSecond) / 1e24).toFixed(6) : '0.000000'} mUSDC/sec</p></Card><Card><p className="text-sm text-slate-400">Pay-period progress</p><div className="mt-4 h-3 overflow-hidden rounded-full bg-white/10"><div className="h-full bg-mint" style={{width:`${progress}%`}}/></div><p className="mt-3 text-sm text-slate-300">{progress.toFixed(1)}% complete · {streaming ? 'Earning now' : pool?.paused ? 'Stream stopped' : 'Not currently streaming'}</p></Card></div><Card><h2 className="font-bold">Withdrawal history</h2><div className="mt-3 space-y-2">{history.length ? history.map((item,i)=><a className="flex justify-between rounded-lg bg-white/5 p-3 text-sm hover:bg-white/10" target="_blank" href={txUrl(item.hash)} key={`${item.hash}-${i}`}><span>{money(item.amount)} mUSDC</span><span className="font-mono text-slate-400">{short(item.hash)}</span></a>) : <p className="py-4 text-sm text-slate-500">No withdrawals yet.</p>}</div></Card></div>; }
